= AI Basketball App

This is an application that will be developed to enable users to upload videos of them shooting a basketball and receive feedback in the application.

== Getting Started

=== Prerequisites

The following dependencies are required to run this application

. Yarn (See https://classic.yarnpkg.com/en/docs/install)
. NodeJs v12.x.x or greater
. expo-cli (To download this, run: `npm install expo-cli --global`)
. expo application on your mobile device (Check the IOS or Android App Store)

=== Local Development

The following steps need to be followed to run the application:

. Install dependencies: `yarn install`
. If you have an Android device, run: `yarn android`
. If you have an IOS device, run: `yarn ios`

After you've started the application for either Android or IOS, expect to see in the terminal a QR code displayed. In the expo application on your mobile device, select 'Scan QR Code' and scan this code. Expect after a shortwhile that the application will load. You should be able to make changes to the application now and once saved, see that change reflected in the mobile application.

