// export const darkTheme = {
//   mode: "dark",
//   PRIMARY_BACKGROUND_COLOR: "#353c51",
//   PRIMARY_TEXT_COLOR: "#767d92",
//   SECONDARY_TEXT_COLOR: "#ffffff",
//   PRIMARY_BUTTON_COLOR: "#152642",
//   SECONDARY_BUTTON_COLOR: "#506680",
// };

export const lightTheme = {
  mode: "light",
  PRIMARY_BACKGROUND_COLOR: "#FFFFFF",
  PRIMARY_TEXT_COLOR: "#000000",
  SECONDARY_TEXT_COLOR: "#5DB075 ",
  INPUT_BACKGROUND_COLOR: "#F6F6F6",
  INPUT_BORDER_COLOR: "#E8E8E8",
  INPUT_COLOR: "#BDBDBD",
  PRIMARY_BUTTON_BACKGROUND_COLOR: "#5DB075",
  PRIMARY_BUTTON_COLOR: "#FFFFFF",
  // SECONDARY_BUTTON_COLOR: "#a1c9f1",
};
