// export const darkTheme = {
//   mode: "dark",
//   PRIMARY_BACKGROUND_COLOR: "#353c51",
//   PRIMARY_TEXT_COLOR: "#767d92",
//   SECONDARY_TEXT_COLOR: "#ffffff",
//   PRIMARY_BUTTON_COLOR: "#152642",
//   SECONDARY_BUTTON_COLOR: "#506680",
// };

export const initialTheme = {
  PRIMARY_BACKGROUND_COLOR: "#FFFFFF",
  PRIMARY_TEXT_COLOR: "#000000",
  SECONDARY_TEXT_COLOR: "#5DB075 ",
  INPUT_BACKGROUND_COLOR: "#F6F6F6",
  INPUT_BORDER_COLOR: "#E8E8E8",
  INPUT_COLOR: "#BDBDBD",
  PRIMARY_BUTTON_BACKGROUND_COLOR: "#5DB075",
  PRIMARY_BUTTON_COLOR: "#FFFFFF",
};

export const lakersPrimaryTheme = {
  PRIMARY_BACKGROUND_COLOR: "#FFFFFF",
  PRIMARY_TEXT_COLOR: "#000000",
  SECONDARY_TEXT_COLOR: "#5DB075 ",
  INPUT_BACKGROUND_COLOR: "#F6F6F6",
  INPUT_BORDER_COLOR: "#E8E8E8",
  INPUT_COLOR: "#BDBDBD",
  PRIMARY_BUTTON_BACKGROUND_COLOR: "#552583",
  PRIMARY_BUTTON_COLOR: "#FDB927",
};

export const lakersSecondaryTheme = {
  PRIMARY_BACKGROUND_COLOR: "#FFFFFF",
  PRIMARY_TEXT_COLOR: "#000000",
  SECONDARY_TEXT_COLOR: "#5DB075 ",
  INPUT_BACKGROUND_COLOR: "#F6F6F6",
  INPUT_BORDER_COLOR: "#E8E8E8",
  INPUT_COLOR: "#BDBDBD",
  PRIMARY_BUTTON_BACKGROUND_COLOR: "#FDB927",
  PRIMARY_BUTTON_COLOR: "#552583",
};

export const bullsPrimaryTheme = {
  PRIMARY_BACKGROUND_COLOR: "#FFFFFF",
  PRIMARY_TEXT_COLOR: "#000000",
  SECONDARY_TEXT_COLOR: "#5DB075 ",
  INPUT_BACKGROUND_COLOR: "#F6F6F6",
  INPUT_BORDER_COLOR: "#E8E8E8",
  INPUT_COLOR: "#BDBDBD",
  PRIMARY_BUTTON_BACKGROUND_COLOR: "#CE1141",
  PRIMARY_BUTTON_COLOR: "#000000",
};

export const bullsSecondaryTheme = {
  PRIMARY_BACKGROUND_COLOR: "#FFFFFF",
  PRIMARY_TEXT_COLOR: "#000000",
  SECONDARY_TEXT_COLOR: "#5DB075 ",
  INPUT_BACKGROUND_COLOR: "#F6F6F6",
  INPUT_BORDER_COLOR: "#E8E8E8",
  INPUT_COLOR: "#BDBDBD",
  PRIMARY_BUTTON_BACKGROUND_COLOR: "#000000",
  PRIMARY_BUTTON_COLOR: "#CE1141",
};

export const themes = {
  initialTheme,
  bullsPrimaryTheme,
  bullsSecondaryTheme,
  lakersPrimaryTheme,
  lakersSecondaryTheme,
};
